### DISCUSSION TITLE
Cannot commit from Magit on Windows 11

### DISCUSSION THREAD

**Discussion by jacobilsoe** [magit/with-editor#109] [Support] [answered]
When I try to do a commit from Magit on Windows 11 Pro 21H2 I get this error:

```
  1 git.exe … "commit" "--"
Aborting commit due to empty commit message.
sh -c 'printf /nWITH-EDITOR:: $$: No such file or directory
```
Versions: Magit 20220331.2308 [>= 3.3.0-git], Git 2.35.1, Emacs 27.2, windows-nt

I installed Emacs 27.2 by just unzipping to a folder.

The value of `with-editor-emacsclient-executable` looks good to me:

```
with-editor-emacsclient-executable:
 value:   c:/Tools/emacs-27.2-x86_64/bin/emacsclient.exe (27.2)
 default: c:/Tools/emacs-27.2-x86_64/bin/emacsclient.exe (27.2)
 funcall: c:/Tools/emacs-27.2-x86_64/bin/emacsclient.exe (27.2)
```

Anything I can try to troubleshoot this further?
